FROM python:3.11-slim

COPY requirements.txt requirements.txt
COPY config.py config.py

RUN python -m venv env
RUN bash env/bin/activate
RUN pip install -r requirements.txt

EXPOSE 4001

COPY ./app ./app

CMD [ "uvicorn", "app.main:app", "--port", "4000", "--host", "0.0.0.0" ]